---
title: "Homework 5"
author: "Paula Wu"
date: "11/15/2021"
output: github_document
---
Import the libraries
```{r, message=FALSE}
library(tidyverse)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 2
```{r, message=FALSE, warning=FALSE}
# read in data sets, store in a data frame
study_df = 
  tibble(rel_path = list.files("./data", pattern = ".csv")) %>% 
  mutate(path = str_c("./data/", rel_path),
         content = map(.x = path, ~read_csv(.x))) %>% 
  separate(rel_path, into = c("arms", "subject_id")) %>% 
  mutate(arms = as.factor(recode(arms, "con" = "control", "exp" = "experiment"))) %>% 
  select(-path) %>% 
  unnest(content)
```
```{r}
# make a spaghetti plot
study_df %>% 
  pivot_longer(week_1:week_8, 
               names_to = "weeks", 
               names_prefix = "week_", 
               values_to = "observations") %>% 
  mutate(weeks = as.numeric(weeks)) %>% 
  ggplot(aes(x = weeks, y = observations, group = subject_id)) +
  geom_line(aes(color = subject_id)) +
  facet_grid(.~arms)
```



## Problem 3
```{r}
set.seed(10)
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) %>% 
  janitor::clean_names()  # just to tidy things up
```
```{r}
# function to address problems
iris_impute = function(col_vec){
  if(is.character(col_vec)){
    col_vec = replace_na(col_vec, "virginica")
  }else if(is.numeric(col_vec)){
    vec_mean = mean(col_vec, na.rm = TRUE)
    col_vec = replace_na(col_vec, vec_mean)
  }
}
iris_filled = 
  map(iris_with_missing, iris_impute) %>% 
  as_tibble() 
iris_filled %>% skimr::skim()
```
Results shown by `skimr::skim()` shows the completeness of the dataset. 
